# Generated by Django 2.2.13 on 2020-06-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='typename',
            field=models.CharField(max_length=20),
        ),
    ]
