# Generated by Django 2.2.13 on 2020-06-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200611_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='stars',
            field=models.FloatField(),
        ),
    ]
