# Generated by Django 2.2.13 on 2020-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200611_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='stars',
            field=models.CharField(max_length=5),
        ),
    ]
