# Generated by Django 2.2.13 on 2020-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200611_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='stars',
            field=models.CharField(max_length=10),
        ),
    ]
